### ISSUE TITLE
Consider release a Nuget package

### ISSUE THREAD

**Issue by gibranrosa** [aosoft/Xamarin.Forms.WinForms#6]
Hi! It would be interesting to release a Nuget package of this repo, because it would help more people to use it, and particularly it would make possible to integrate some samples of a new F# library for functional cross-platform GUI called Elmish.Xamarin.Forms, that the creator of F# is developing.

**Comment by aosoft** [comment]
I would like to consider after development progresses.

**Comment by amirvenus** [comment]
Has there been any update?

I believe this will be one of the most wanted libraries!

**Comment by aosoft** [comment]
I planned to release a nuget package when Issue #9 and #10 was closed.
However, since these Issues can not be implemented immediately, I would like to give priority to the release of nuget package.

**Comment by aosoft** [comment]
I released nuget packages.

https://www.nuget.org/packages/Xamarin.Forms.Platform.WinForms/
https://www.nuget.org/packages/SkiaSharp.Views.Forms.WinForms/
